# Generated by Django 5.2 on 2025-05-26 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_transactions', to='api.loyaltyaccount'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='origin_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_transactions', to='api.loyaltyaccount'),
        ),
    ]
