# Generated by Django 5.2 on 2025-05-27 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pointstransaction_destination_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointstransaction',
            options={'ordering': ['-transaction_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='pointstransaction',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='pointstransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pointstransaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo monetário associado à transação.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='description',
            field=models.CharField(blank=True, help_text='Uma breve descrição ou motivo para a transação', max_length=255),
        ),
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='average_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo médio por milheiro', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='custom_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cotação personalizada por milheiro para avaliação de valor', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='last_updated',
            field=models.DateTimeField(help_text='Data da última atualização de saldo/informações desta conta no programa de fidelidade'),
        ),
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_accounts', to='api.loyaltyprogram'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Quantidade de pontos/milhas. Sempre positivo. O tipo da transação define se é crédito ou débito.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='bonus_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de bônus em transferências (ex: 100.00 para 100%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de registro da transação'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, help_text='Conta para onde os pontos/milhas foram (para Inclusão Manual, Transferência, Ajuste de crédito)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='api.loyaltyaccount'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='origin_account',
            field=models.ForeignKey(blank=True, help_text='Conta de onde os pontos/milhas saíram (para Transferência, Resgate, Venda, Expiração, Ajuste de débito)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='api.loyaltyaccount'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_date',
            field=models.DateTimeField(help_text='Data e hora em que a transação efetivamente ocorreu no programa de fidelidade'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Inclusão Manual'), (2, 'Transferência'), (3, 'Resgate'), (4, 'Venda de Milhas'), (5, 'Expiração de Pontos'), (6, 'Ajuste de Saldo')]),
        ),
        migrations.AlterUniqueTogether(
            name='loyaltyaccount',
            unique_together={('wallet', 'program', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='userwallet',
            unique_together={('user', 'wallet_name')},
        ),
    ]
