# Generated by Django 5.2 on 2025-11-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pointstransaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyaccount',
            name='custom_rate',
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='custom_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor de mercado estimado por 1.000 milhas/pontos', max_digits=10),
        ),
    ]
